name: Release gitwt

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create directory for release files
      run: mkdir -p release-files/gitwt

    - name: Copy selected files to release directory
      run: |
        cp README.md release-files/gitwt/
        cp gitwt release-files/gitwt/

    - name: Create zip archive
      run: zip -r gitwt.zip release-files/gitwt

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload zip archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitwt.zip
        asset_name: gitwt.zip
        asset_content_type: application/zip
